### ISSUE TITLE
The app crashed when I tried to cancel the pin changing process by pressing the back button

### ISSUE THREAD

**Issue by sagorahmed** [hoanghiephui/Bitcoin-Wallet#1]
#### Expected behavior
I expected that the app would not crash when I canceled the pin changing process by pressing the back button. 
I believe the users should be able to press the back button during that encryption process.

#### Actual behavior
When I tried to change my pin and pressed the back button during that process, then the app crashes immediately.

#### How to reproduce
1. Open the app.
2. Click on ⋮ (Three dots/ Vertical ellipsis).
3. Then click on "Change Pin Code" and fill these fields with the valid pin. 
4. Then press "EDIT", and then press the back button immediately and notice the bug.

* App version: 1.1.3
* Operating system: Android 6.0.1

#### Recording Of The Bug
![bug](https://media.giphy.com/media/JOACXBphUmzaeQb1HA/giphy.gif)

#### LogCat
```
05-17 14:33:31.464 24995 25180 E AndroidRuntime: FATAL EXCEPTION: backgroundThread

05-17 14:33:31.464 24995 25180 E AndroidRuntime: Process: com.bitcoin.wallet.btc, PID: 24995

05-17 14:33:31.464 24995 25180 E AndroidRuntime: java.lang.IllegalStateException: Fragment EncryptKeysDialogFragment{e59cdde} not attached to an activity.

05-17 14:33:31.464 24995 25180 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:724)

05-17 14:33:31.464 24995 25180 E AndroidRuntime: 	at com.bitcoin.wallet.btc.ui.fragments.EncryptKeysDialogFragment$handleGo$1.run(EncryptKeysDialogFragment.kt:98)

05-17 14:33:31.464 24995 25180 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

05-17 14:33:31.464 24995 25180 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

05-17 14:33:31.464 24995 25180 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

05-17 14:33:31.464 24995 25180 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by hoanghiephui** [comment]
Hi @sagorahmed 
Thank you for your feedback. I'll fix

**Comment by sagorahmed** [comment]
Hello @hoanghiephui 
Thanks for your reply.
