### ISSUE TITLE
[Bitcoin-Wallet][v0.1.1.3]The app crashes if I click on request Btc

### ISSUE THREAD

**Issue by 44asad** [hoanghiephui/Bitcoin-Wallet#10]
#### Actual behavior
When I tried to request Btc option, then the app crashes immediately.

#### Expected behavior

I expected that the app would not crash when I click on request btc.I believe the users should be able to press the request btc during that encryption process.

#### How to reproduce:
* Download the app and open it
* click Naw request btc
* see bug
#### Recording Of The Bug:
https://youtu.be/wyAxG1G5d_k

### Test Environment:
Device:samsung J5
OS: Android 6.0.1
Version: v1.1.3
### Logcat:
<pre><code>05-18 03:19:18.515 19564 19564 E AndroidRuntime: FATAL EXCEPTION: main

05-18 03:19:18.515 19564 19564 E AndroidRuntime: Process: com.bitcoin.wallet.btc, PID: 19564

05-18 03:19:18.515 19564 19564 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bitcoin.wallet.btc/com.bitcoin.wallet.btc.ui.activitys.RequestCoinActivity}: android.view.InflateException: Binary XML file line #83: Binary XML file line #83: Error inflating class TextView

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3352)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:223)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7231)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #83: Binary XML file line #83: Error inflating class TextView

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:551)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:429)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:380)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at com.bitcoin.wallet.btc.base.BaseActivity.onCreate(BaseActivity.kt:38)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6877)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3209)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	... 9 more

05-18 03:19:18.515 19564 19564 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #83: Error inflating class TextView

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:527)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	... 17 more

05-18 03:19:18.515 19564 19564 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0800b7

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.content.res.Resources.getResourceName(Resources.java:3677)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:4178)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:4085)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:3935)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:886)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:1193)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:950)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:87)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:83)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:177)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:102)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:758)

05-18 03:19:18.515 19564 19564 E AndroidRuntime: 	... 21 more</code></pre>

**Comment by 44asad** [comment]
@hoanghiephui
pleased  review?

**Comment by hoanghiephui** [comment]
The update is available on Google Play, please confirm again.
