### ISSUE TITLE
 [Bitcoin-Wallet][v0.1.1.3]The app crashes when trying to sent btc

### ISSUE THREAD

**Issue by 44asad** [hoanghiephui/Bitcoin-Wallet#2]
### Actual behavior

When I tried to sent Btc option, then the app crashes immediately.

### Expected behavior
The application should not crash when I click on sent btc option.

### How to reproduce:
* Download the app and open it
* click Naw sent Btc 
* see bug

#### Recording Of The Bug::
https://youtu.be/bF5z0gosPnM

### Test Environment:
* Device:samsung J5
* OS: Android 6.0.1
* Version:  v1.1.3

## My GitHub account:
https://github.com/44asad

### Logcat:

<pre><code>05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widge</code></pre>

**Comment by hoanghiephui** [comment]
@44asad Thanks for your feedback. I'll fix

**Comment by 44asad** [comment]
ok sir!
