### ISSUE TITLE
[v0.1.1.3]The app crashes if I click on "setting"

### ISSUE THREAD

**Issue by 44asad** [hoanghiephui/Bitcoin-Wallet#3]
### Expected behavior
The application should not crash when I click on setting.

### Actual behavior:
The application is crash when I click on "setting"

### How to reproduce:
* Download the app and open it
* click Naw menu icon
* Then click naw "setting"
* see bug

#### Recording Of The Bug:

https://youtu.be/t1Ru-LB3HbE

### Test Environment:
* Device:samsung J5
* OS: Android 6.0.1
* Version:  v1.1.3

### Logcat:
<pre><code>05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.View.layout(View.java:17972)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.view.ViewGroup.layout(ViewGroup.java:5814)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
05-18 03:13:32.025 16873 16873 E AndroidRuntime:   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
</code></pre>

**Comment by 44asad** [comment]
@hoanghiephui
pleased  review?

**Comment by hoanghiephui** [comment]
The update is available on Google Play, please confirm again.
