### ISSUE TITLE
 [Bitcoin-Wallet][v0.1.1.3]The app crashes if I click on "Transactions icon"

### ISSUE THREAD

**Issue by 44asad** [hoanghiephui/Bitcoin-Wallet#5]
### Expected behavior
I expected that the app would not crash when I click on transaction icon.I believe the users should be able to press the transactions icon during that encryption process.

### Actual behavior:
The application is crash when I click on "Transaction"

### How to reproduce:
* Download the app 
* Open the app
* Then click naw "Transactions icon"
* see bug

#### Recording Of The Bug:

https://youtu.be/06aex8GhCok

### Test Environment:
* Device:samsung J5
* OS: Android 6.0.1
* Version:  v1.1.3

### Logcat:
<pre><code>05-18 03:07:50.965 14278 14278 E AndroidRuntime: FATAL EXCEPTION: main
05-18 03:07:50.965 14278 14278 E AndroidRuntime: Process: com.bitcoin.wallet.btc, PID: 14278
05-18 03:07:50.965 14278 14278 E AndroidRuntime: android.view.InflateException: Binary XML file line #82: Binary XML file line #82: Error inflating class com.google.android.material.textfield.TextInputLayout
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at com.bitcoin.wallet.btc.base.BaseBottomSheetDialogFragment.onCreateView(BaseBottomSheetDialogFragment.kt:50)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-18 03:07:50.965 14278 14278 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #82: Error inflating class com.google.android.material.textfield.TextInputLayout
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.createView(LayoutInflater.java:657)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.inflate(LayoutInflater.java:527)05-18 03:07:50.965 14278 14278 E AndroidRuntime:   ... 19 more
05-18 03:07:50.965 14278 14278 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at java.lang.reflect.Constructor.newInstance(Native Method)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.view.LayoutInflater.createView(LayoutInflater.java:631)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   ... 26 more
05-18 03:07:50.965 14278 14278 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/design_password_eye.xml from drawable resource ID #0x7f080090
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.content.res.Resources.loadDrawableForCookie(Resources.java:4216)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.content.res.Resources.loadDrawable(Resources.java:4085)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.content.res.Resources.getDrawable(Resources.java:2005)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.content.res.Resources.getDrawable(Resources.java:1987)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at android.content.Context.getDrawable(Context.java:464)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
05-18 03:07:50.965 14278 14278 E AndroidRuntime:   at androidx.appcompat.widget.TintTypedArray.getDrawable(TintTypedArray.java:76)
05-18 03:07:50.965 14278 14278 E Andro</code></pre>

**Comment by 44asad** [comment]
@hoanghiephui
pleased  review

**Comment by hoanghiephui** [comment]
The update is available on Google Play, please confirm again.
