### ISSUE TITLE
(BUG) The application crashes when I click on Restore Wallet

### ISSUE THREAD

**Issue by facebook-786** [hoanghiephui/Bitcoin-Wallet#6]
# Project Information

* Repository: https://github.com/hoanghiephui/Bitcoin-Wallet
* Project Name: Bitcoin-Wallet

# Expected behavior

When I click on the Restore Wallet, the option should be displayed further from where I store my Wallet

# Actual behavior
The application crashes when I click on Restore Wallet

# How to reproduce

1-[Download ](https://play.google.com/store/apps/details?id=com.bitcoin.wallet.btc)the app and open it
2-Click the arrow to the bottom right side
3- see bug 

* Browser/App version:  Current Version 1.1.7
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190518_174628](https://user-images.githubusercontent.com/50115498/57970045-48029d00-7931-11e9-8b83-31c11ecd49b5.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(28111): FATAL EXCEPTION: main

E/AndroidRuntime(28111): Process: com.bitcoin.wallet.btc, PID: 28111

E/AndroidRuntime(28111): android.content.res.Resources$NotFoundException: Resource ID #0x7f0800e0

E/AndroidRuntime(28111): 	at android.content.res.Resources.getValue(Resources.java:1542)

E/AndroidRuntime(28111): 	at android.content.res.Resources.getDrawable(Resources.java:1046)

E/AndroidRuntime(28111): 	at android.content.res.Resources.getDrawable(Resources.java:1032)

E/AndroidRuntime(28111): 	at android.content.Context.getDrawable(Context.java:403)

E/AndroidRuntime(28111): 	at android.widget.TextView.setCompoundDrawablesWithIntrinsicBounds(TextView.java:2224)

E/AndroidRuntime(28111): 	at com.bitcoin.wallet.btc.ui.adapter.TransactionsWalletAdapter.onBindViewHolder(TransactionsWalletAdapter.kt:239)

E/AndroidRuntime(28111): 	at com.bitcoin.wallet.btc.ui.adapter.TransactionsWalletAdapter.onBindViewHolder(TransactionsWalletAdapter.kt:259)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1888)

E/AndroidRuntime(28111): 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:407)

E/AndroidRuntime(28111): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)

E/AndroidRuntime(28111): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)

E/AndroidRuntime(28111): 	at android.view.Choreographer.doFrame(Choreographer.java:549)

E/AndroidRuntime(28111): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)

E/AndroidRuntime(28111): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime(28111): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime(28111): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(28111): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(28111): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(28111): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(28111): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(28111): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by facebook-786** [comment]
hello sir
@hoanghiephui 
pleased review my contribution

**Comment by hoanghiephui** [comment]
Thank you for your feedback. The update is available on Google Play, please check again.

**Comment by facebook-786** [comment]
Thanks your sir bug has been fixed now

**Comment by facebook-786** [comment]
Thank you sir bug has been fixed now

**Comment by hoanghiephui** [comment]
@facebook-786 Please rate the app, if it works for you!
