### ISSUE TITLE
(BUG) Bitcoin-Wallet The application crashes when I click the set pin code

### ISSUE THREAD

**Issue by facebook-786** [hoanghiephui/Bitcoin-Wallet#7]
# Project Information

* Repository: https://github.com/hoanghiephui/Bitcoin-Wallet
* Project Name: Bitcoin-Wallet

# Expected behavior
When I click the set pin code, a window should appear next to where I can enter my secret pin as security.

# Actual behavior

After opening the application, click on the horizontal dot at the bottom right and then when I click the set pin code the application is crashed.

# How to reproduce

1-[Download ](https://play.google.com/store/apps/details?id=com.bitcoin.wallet.btc)the app and open it
2- Click the three horizontal line at the bottom right
3- And click set pin code option
4- see bug 

* Browser/App version:  Current Version 1.1.7
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190518_180053](https://user-images.githubusercontent.com/50115498/57970136-ada35900-7932-11e9-87a0-1c98f90b51e8.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime(31784): FATAL EXCEPTION: main

E/AndroidRuntime(31784): Process: com.bitcoin.wallet.btc, PID: 31784

E/AndroidRuntime(31784): android.app.RemoteServiceException: Bad notification posted from package com.bitcoin.wallet.btc: Couldn't create icon: StatusBarIcon(pkg=com.bitcoin.wallet.btcuser=0 id=0x7f0800c8 level=0 visible=true num=0 )

E/AndroidRuntime(31784): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)

E/AndroidRuntime(31784): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(31784): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(31784): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(31784): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(31784): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(31784): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(31784): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by facebook-786** [comment]
hello 
@hoanghiephui 
pleased review my contribution

**Comment by facebook-786** [comment]
hello 
@hoanghiephui 
pleased review my contribution

**Comment by hoanghiephui** [comment]
Thank you for your feedback. The update is available on Google Play, please check again.

**Comment by facebook-786** [comment]
Thank you sir bug has been fixed now in the latest version
