### ISSUE TITLE
(BUG) Bitcoin-Wallet  When I click on the Back up Wallet, the application is crashed

### ISSUE THREAD

**Issue by facebook-786** [hoanghiephui/Bitcoin-Wallet#8]
# Project Information

* Repository: https://github.com/hoanghiephui/Bitcoin-Wallet
* Project Name: Bitcoin-Wallet

# Expected behavior

When I click Back up Wallet, the further option to back up Wallet should be displayed from where I can make my wallet backup.

# Actual behavior

When I click on the Backup Wallet, the application is crashed

# How to reproduce

1-[Download ](https://play.google.com/store/apps/details?id=com.bitcoin.wallet.btc)the app and open it
2-Click the Backup Wallet icon at the bottom right
3- see bug

* Browser/App version:  Current Version 1.1.7
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![20190518_195908](https://user-images.githubusercontent.com/50115498/57971489-bc463c00-7943-11e9-90f1-f081d4d5a110.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime( 2534): FATAL EXCEPTION: main

E/AndroidRuntime( 2534): Process: com.bitcoin.wallet.btc, PID: 2534

E/AndroidRuntime( 2534): android.app.RemoteServiceException: Bad notification posted from package com.bitcoin.wallet.btc: Couldn't create icon: StatusBarIcon(pkg=com.bitcoin.wallet.btcuser=0 id=0x7f0800c8 level=0 visible=true num=0 )

E/AndroidRuntime( 2534): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)

E/AndroidRuntime( 2534): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime( 2534): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 2534): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime( 2534): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 2534): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 2534): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime( 2534): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
</code></pre>

**Comment by facebook-786** [comment]
hello 
@hoanghiephui 
pleased review my contribution

**Comment by hoanghiephui** [comment]
Thank you for your feedback. The update is available on Google Play, please check again.

**Comment by facebook-786** [comment]
Thank you sir bug has been fixed now

**Comment by hoanghiephui** [comment]
@facebook-786 Please rate the app, if it works for you!
