### ISSUE TITLE
(BUG) Bitcoin-Wallet The application crashes when I click on the sweep Paper Wallet

### ISSUE THREAD

**Issue by facebook-786** [hoanghiephui/Bitcoin-Wallet#9]
# Project Information

* Repository: https://github.com/hoanghiephui/Bitcoin-Wallet
* Project Name: Bitcoin-Wallet

# Expected behavior

When I click on the Sweep Paper Wallet, the application should not crash, but the Sweep paper Wallet should appear next.

# Actual behavior

The application crashes when I click on the sweep Paper Wallet
# How to reproduce

1-[Download ](https://play.google.com/store/apps/details?id=com.bitcoin.wallet.btc)the app and open it
2-Click the three horizontal line at the bottom right
3- Click the Sweep Paper Wallet
4- see bug

* Browser/App version:  Current Version 1.1.7
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug
![20190518_200749](https://user-images.githubusercontent.com/50115498/57971532-2c54c200-7944-11e9-9715-5f2917155114.gif)

# My Github Account
https://github.com/facebook-786

# Logcat

<pre><code>E/AndroidRuntime( 4693): FATAL EXCEPTION: main

E/AndroidRuntime( 4693): Process: com.bitcoin.wallet.btc, PID: 4693

E/AndroidRuntime( 4693): android.view.InflateException: Binary XML file line #46: Error inflating class com.google.android.material.textfield.TextInputLayout

E/AndroidRuntime( 4693): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)

E/AndroidRuntime( 4693): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)

E/AndroidRuntime( 4693): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)

E/AndroidRuntime( 4693): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)

E/AndroidRuntime( 4693): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

E/AndroidRuntime( 4693): 	at com.bitcoin.wallet.btc.base.BaseBottomSheetDialogFragment.onCreateView(BaseBottomSheetDialogFragment.kt:50)

E/AndroidRuntime( 4693): 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)

E/AndroidRuntime( 4693): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)

E/AndroidRuntime( 4693): 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)

E/AndroidRuntime( 4693): 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)

E/AndroidRuntime( 4693): 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)

E/AndroidRuntime( 4693): 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)

E/AndroidRuntime( 4693): 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)

E/AndroidRuntime( 4693): 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)

E/AndroidRuntime( 4693): 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)

E/AndroidRuntime( 4693): 	at androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)

E/AndroidRuntime( 4693): 	at android.os.Handler.handleCallback(Handler.java:739)

E/AndroidRuntime( 4693): 	at android.os.Handler.dispatchMessage(Handler.java:95)

E/AndroidRuntime( 4693): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime( 4693): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime( 4693): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime( 4693): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime( 4693): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime( 4693): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime( 4693): Caused by: java.lang.reflect.InvocationTargetException

E/AndroidRuntime( 4693): 	at java.lang.reflect.Constructor.newInstance(Native Method)

E/AndroidRuntime( 4693): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)

E/AndroidRuntime( 4693): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)

E/AndroidRuntime( 4693): 	... 23 more

E/AndroidRuntime( 4693): Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v21/design_password_eye.xml from drawable resource ID #0x7f080090

E/AndroidRuntime( 4693): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2946)

E/AndroidRuntime( 4693): 	at android.content.res.Resources.loadDrawable(Resources.java:2821)

E/AndroidRuntime( 4693): 	at android.content.res.Resources.getDrawable(Resources.java:1050)

E/AndroidRuntime( 4693): 	at android.content.res.Resources.getDrawable(Resources.java:1032)

E/AndroidRuntime( 4693): 	at android.content.Context.getDrawable(Context.java:403)

E/AndroidRuntime( 4693): 	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)

E/AndroidRuntime( 4693): 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)

E/AndroidRuntime( 4693): 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)

E/AndroidRuntime( 4693): 	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)

E/AndroidRuntime( 4693): 	at androidx.appcompat.widget.TintTypedArray.getDrawable(TintTypedArray.java:76)

E/AndroidRuntime( 4693): 	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:344)

E/AndroidRuntime( 4693): 	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:247)

E/AndroidRuntime( 4693): 	... 26 more

E/AndroidRuntime( 4693): Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f08008e

E/AndroidRuntime( 4693): 	at android.content.res.Resources.getResourceName(Resources.java:2413)

E/AndroidRuntime( 4693): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2908)

E/AndroidRuntime( 4693): 	at android.content.res.Resources.loadDrawable(Resources.java:2821)

E/AndroidRuntime( 4693): 	at android.content.res.Resources.loadDrawable(Resources.java:2670)

E/AndroidRuntime( 4693): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:761)

E/AndroidRuntime( 4693): 	at android.graphics.drawable.AnimatedStateListDrawable.parseItem(AnimatedStateListDrawable.java:503)

E/AndroidRuntime( 4693): 	at android.graphics.drawable.AnimatedStateListDrawable.inflateChildElements(AnimatedStateListDrawable.java:4
</code></pre>

**Comment by facebook-786** [comment]
hello sir 
@hoanghiephui 
pleased review my contribution

**Comment by hoanghiephui** [comment]
Thank you for your feedback. The update is available on Google Play, please check again.

**Comment by facebook-786** [comment]
Thank you sir bug has been fixed now  in the latest version

**Comment by hoanghiephui** [comment]
@facebook-786 Please rate the app, if it works for you!
